repos:
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
-   repo: local
    hooks:
    -   id: pytest
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
