language: python
python:
- "2.7"
- "3.6"
- "3.7"
addons:
  apt:
    packages:
      - oracle-java8-set-default
install: pip install --upgrade -r dev-requirements.txt
script:  pre-commit run --all-files
notifications:
  email:
    on_success: never
