language: python
python:
- "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jdk
install: pip install --upgrade -r dev-requirements.txt
script:  pre-commit run --all-files
notifications:
  email:
    on_success: never
